import Head from "next/head";
// import Scene from "~/components/HackTimeLogo";
import Spline from "@splinetool/react-spline";

export default function Home() {
  return (
    <>
      <Head>
        <title>hacktime</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div> it is hacktime</div>

      {/* <Scene /> */}

      <Spline scene="https://prod.spline.design/vC6L8LFnvRbgMcAo/scene.splinecode" />
    </>
  );
}
